name: AFK
version: 2.6.1
author: MrTransistor
main: plugin.mrtransistor.AFK.AFK
commands:
  AFKUtils:
    usage: "Usage: /afkutils controlbot <name>"
    description: "Allows players to control bots"
  spawnBot:
    usage: "Usage: /spawnbot <name>"
    description: "Spawns an NPC, that can be controlled from within the plugin, which acts as a player, allowing loading mobs and random ticking"
  removeBot:
    usage: "Usage: /removebot <name>"
    description: "Removes all bots with specified name"
  removeAllBots:
    usage: "Usage: /removeallbots"
    description: "Removes all bots"
api-version: 1.17