name: ${name}
version: ${version}
author: ${author}
main: ${mainClassPath}
commands:
  afkutils:
    usage: "Usage: /afkutils controlBot <name>"
    description: "Allows players to control bots"
    tabCompletion: [ controlBot ]
    args:
      controlBot:
        tabCompletion: [ ]
        __text__:
          tabCompletion: [ attackOnce, shootNearest, toggle ]
          attackOnce:
            tabCompletion: [ ]
            handler: attackOnce
          shootNearest:
            tabCompletion: [ ]
            handler: shootNearest
          toggle:
            tabCompletion: [ attackContinuous, selfDefence, setForcePoI, ticking ]
            attackContinuous:
              tabCompletion: [ ]
              handler: attackContinuous
            selfDefence:
              tabCompletion: [ ]
              handler: selfDefence
            setForcePoI:
              tabCompletion: [ ]
              handler: setForcePoI
            ticking:
              tabCompletion: [ ]
              handler: ticking

  spawnbot:
    usage: "Usage: /spawnbot <name>"
    description: "Spawns an NPC, that can be controlled from within the plugin, which acts as a player, allowing loading mobs and random ticking"
    tabCompletion: [ ]
    args:
      __text__:
        tabCompletion: [ ]
        handler: spawnBot
  removeallbots:
    usage: "Usage: /removeallbots"
    description: "Removes all bots"
    tabCompletion: [ ]
    handler: removeAllBots
api-version: ${apiVersion}